Implemented pages 1 and 2 of mockup
thoth-station/odh-dashboard pull request #2
Opened 2022-10-25 19:38 UTC by Gkrumbach07

## Related Issues and Dependencies

https://github.com/thoth-station/opendatahub-cnbi/issues/18

## This introduces a breaking change

- No

## This Pull Request implements

- convert add image modal to to a page
- add breadcrumbs
- add dropdown for different image adding methods
- update state management to use useReducer
- added more columns to image table
- validation blocks submit button
- error header when api fails to respond after submit (500 code)
- small changes to wording

### Description

This PR implements the first two pages of the mockup. Essentially it updates the BYON implementation so that is able to support multiple methods of image adding.

2022-10-25 19:38 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fodh-dashboard).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/odh-dashboard/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-10-28 11:05 UTC, codificat requested changes
This looks great, thanks!

I only have one comment about RHODS vs ODH

2022-10-28 11:05 UTC, codificat commented on frontend/src/pages/BYONImages/AddNewImageForm.tsx
> +        description="Add a new image to Red Hat Data Science
I believe this should be:
```suggestion
        description="Add a new image to Open Data Hub
```

but beyond that: is there a better place to set the product name globally? (thinking in moving this downstream later)

2022-10-28 12:54 UTC, Gkrumbach07 commented on frontend/src/pages/BYONImages/AddNewImageForm.tsx
> +        description="Add a new image to Red Hat Data Science
that is the only place red hat data science is mentioned. Although we could set some global variable, it is not needed if it isnt used much

2022-10-28 19:26 UTC, codificat commented
#3 adds CI configuration, that should let the required pre-commit run and allow me to `/approve`. Once that merges, a rebase should help us push this one forward. I'd take the opportunity to squash the 3 commits into one (or at least the last one with 7b28e816309721011cd0bc735a67017c809b1aab)

2022-10-31 14:36 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from gkrumbach07 by writing `/assign @gkrumbach07` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fodh-dashboard).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/odh-dashboard/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["gkrumbach07"]} -->

2022-10-31 14:38 UTC, sesheta commented
@Gkrumbach07: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 5047561796d6fcfbb080d0a48c56a0e654f66cbb | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/thoth-station_odh-dashboard/2/pre-commit/1587091218511171584) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=odh-dashboard&pr=2). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGkrumbach07). Please help us and [open an issue](https://github.com/thoth-station/odh-dashboard/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-11-03 13:25 UTC, closed without merging

2022-11-03 13:25 UTC, Gkrumbach07 commented
replaced by https://github.com/thoth-station/odh-dashboard/pull/4